# Generated by Django 3.0.6 on 2020-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='figure',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='figurelink',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='figurelink',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
