# Generated by Django 3.0.6 on 2020-06-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200609_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Money',
        ),
    ]
