# Generated by Django 3.0.6 on 2020-06-09 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_user', to=settings.AUTH_USER_MODEL)),
                ('s_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
